services:
  go:
    build: ./server
    container_name: server
    ports:
      - 8080:8080
    networks:
      - app-network
    volumes:
      - ./server:/app
    restart: always

  postgres:
    image: mongo
    ports:
      - 27017:27017
    container_name: mongo
    volumes:
      - ./data/db:/data/db
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge